from geo_utils import *
gw = GeoWriter("myTestFile.txt","test_data")
gw.beginFeatureCol()
gw.beginFeature()
gw.beginProperties()
gw.addLine("here's a line with a comma,")
gw.addLine("here's another line with a comma,")
gw.endProperties()
gw.endFeature()
gw.endFeatureCol()
gw.endFile()